version: "3"
services:
    install:
        user: node
        image: node:18
        volumes:
            - .:/app
        command: bash -c "cd /app && rm -rf node_modules && rm -f package-lock.json && npm i"
    build:
        # user: node
        image: node:18
        volumes:
            - .:/app
        command: bash -c "cd /app && npm run build"
    serve:
        user: root
        cap_add:
            - SYS_ADMIN
        image: ghcr.io/puppeteer/puppeteer:22.7.0
        ports:
            - 8200:8200
        volumes:
            - .:/app
        command: bash -c "cd /app && node node_modules/puppeteer/install.mjs && npm run start"
    test:
        user: root
        cap_add:
            - SYS_ADMIN
        image: ghcr.io/puppeteer/puppeteer:22.10.0
        volumes:
            - .:/app
        command: bash -c "cd /app && node node_modules/puppeteer/install.mjs && npm run test"
        

